spring:
  datasource:
    url: jdbc:h2:mem:coronavirus_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: medeirosavio
    password: 1234babi
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    br:
      com:
        savio:
          project: DEBUG
